var globalTypeText = "text"
var globalTypeNumber = "number"
var globalTypeImage = "image"
var globalTypeTime = "time"
var globalTypeNumber = "number"
var globalTypeUser = "user"
var globalTypeBool = "bool"
