version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: resultra-postgres
    volumes:
      - /var/resultra/appdata/database:/var/lib/postgresql/data
    restart: always
  web:
    depends_on:
      - db
    image: resultra-server:latest
    build:
      context: .
    container_name: resultra-server
    volumes:
      - /var/resultra:/var/resultra
    ports:
      - "${RESULTRA_HOST_PORT:-80}:80"
    restart: always
