application: datasheet
version: 1
runtime: go
api_version: go1

handlers:
- url: /dashboard
  static_dir: dashboard
- url: /common
  static_dir: common
- url: /field
  static_dir: field
- url: /home
  static_dir: home
- url: /filter
  static_dir: filter
- url: /form
  static_dir: form
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /image
  static_dir: image
- url: /.*
  script: _go_app