package inputProperties

var TemplateFileList = []string{"static/admin/common/inputProperties/numberSpinner.html",
	"static/admin/common/inputProperties/numberValidation.html",
	"static/admin/common/inputProperties/textInputValidation.html",
	"static/admin/common/inputProperties/dateValidation.html",
	"static/admin/common/inputProperties/dateFormat.html",
	"static/admin/common/inputProperties/checkBoxFormat.html",
	"static/admin/common/inputProperties/checkBoxValidation.html",
	"static/admin/common/inputProperties/ratingFormat.html",
	"static/admin/common/inputProperties/ratingTooltip.html",
	"static/admin/common/inputProperties/toggleFormat.html",
	"static/admin/common/inputProperties/colorScheme.html",
	"static/admin/common/inputProperties/userSelectionValidation.html",
	"static/admin/common/inputProperties/formButtonBehavior.html",
	"static/admin/common/inputProperties/clearValue.html",
	"static/admin/common/inputProperties/helpPopup.html",
	"static/admin/common/inputProperties/userSelectionRoles.html",
	"static/admin/common/inputProperties/userSelectionCurrUser.html",
	"static/admin/common/inputProperties/progressRange.html",
	"static/admin/common/inputProperties/socialButtonFormat.html"}
